name = "coinrush"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# [vars]
# MY_VARIABLE = "production_value"
[[d1_databases]]
binding = "DB"
database_name = "coinrush"
database_id = "7b1fcee4-03f9-43e5-a6c4-a0bc1d825fa5"
migrations_dir = "./src/db/migrations"
